# Site settings
email: info@redaubs.tech
title: Red Aubs Tech
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://redaubs-tech.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  
google_play: ''
google_plus_com: ''  # Community link
google_plus_per: ''  #Personal link
facebook_app_id: 

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Current Website
    link: redaubs.tech
  option2:
    name: 
    link: 
  option3:
    name: 
    link: 

disqus: false
disqus_shortname: 'redaubstech'

# Build settings
markdown: kramdown
